language: node_js
node_js:
  - 10

cache:
  directories:
    - $(jq -r .jest.cacheDirectory package.json)

script:
  - npm run lint
  - travis_wait 30 npm test
  - npm run dist
  - npm run build

notifications:
    slack: github:4OisIoqZYyMlWcw3hFtZgbmh
