---
trigger: release-blocker
title: Release Blocker
description: Describe the issue(s) preventing a release from being published
surfaces:
  - issue
steps:
  - type: form
    style: embedded
    body:
      - type: textarea
        attributes:
          id: blocker-description
          label: Description
          placeholder: Describe the issue that prevents the release from being published.

      - type: dropdown
        attributes:
          id: blocker-type
          label: Type
          description: Specify the type(s) of changes that prevent the release from being published.
          multiple: true
          options:
            - 'Component removed'
            - 'Type removed'
            - 'Type incompatability'
            - 'Other'

      - type: input
        id: other
        attributes:
          label: Other
          description: 'Provide a custom blocker type if other was used above'

      - type: textarea
        attributes:
          id: pull-requests-to-revert
          label: Pull Requests
          placeholder: Provide one or more Pull Requests that need to be reverted in order to publish the release.

      - type: checkboxes
        id: confirm
        attributes:
          label: Please confirm the following
          options:
            - label: I have re-opened any issues that were closed due to the reverted Pull Requests
              required: true
            - label: I have left a comment on these issues with a link to the reverted Pull Request
              required: true
