name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --coverage

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run test:type-check

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install examples dependencies
        working-directory: examples/nextjs
        run: npm ci

      - name: Build examples
        working-directory: examples/nextjs
        run: npm run build

  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build storybook
        run: npx build-storybook
      - uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: storybook-static

  vrt-runner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    needs: storybook
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook-static
      - name: Run storybook
        id: storybook
        run: |
          npx serve -l 6006 storybook-static &
          pid=$!
          echo "pid=$pid" >> $GITHUB_OUTPUT
          sleep 5
      - name: Run VRT
        run: npx playwright test --grep @vrt --shard="${{ matrix.shard }}/2"
      - name: Stop storybook
        run: kill ${{ steps.storybook.outputs.pid }}
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: vrt-${{ matrix.shard }}
          path: .playwright/report

  vrt:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: vrt-runner
    steps:
      - name: Check VRT Runner job status
        if: ${{ needs.vrt-runner.result != 'success' }}
        run: exit 1

  aat:
    runs-on: ubuntu-latest
    needs: storybook
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook-static
      - name: Run storybook
        id: storybook
        run: |
          npx serve -l 6006 storybook-static &
          pid=$!
          echo "pid=$pid" >> $GITHUB_OUTPUT
          sleep 5
      - name: Run AAT
        run: npx playwright test --grep @aat
      - name: Stop storybook
        run: kill ${{ steps.storybook.outputs.pid }}
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: aat
          path: .playwright/report
