name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  guard:
    name: Guard
    runs-on: ubuntu-latest
    outputs:
      # To avoid deploying documentation for unrelease changes, we check the number of changeset files.
      # If it's 0, we deploy.
      should_deploy: ${{ steps.changeset-count.outputs.change_count == 0 }}
    steps:
      - uses: actions/checkout@v3

      - id: changeset-count
        run: echo "::set-output name=change_count::$(ls .changeset/*.md | grep -v README | wc -l | xargs)"

      # Log changeset count for debugging purposes
      - name: Log changeset count
        run: echo ${{ steps.changeset-count.outputs.change_count }}

      # Log guard output for debugging purposes
      - name: Log guard output
        run: echo ${{ needs.guard.outputs.should_deploy }}

  deploy:
    name: Production
    needs: [guard]
    if: ${{ needs.guard.outputs.should_deploy == 'true' }}
    uses: primer/.github/.github/workflows/deploy.yml@0cec9b9914f358846163f2428663b58da41028c9
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 16
      install: npm ci && cd docs && npm ci && cd ..
      build: npm run build:docs
      output_dir: docs/public
