name: Deploy
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    if: ${{ github.repository == 'primer/react' }}
    name: Preview
    uses: primer/.github/.github/workflows/deploy_preview.yml@main
    with:
      node_version: 16
      install: npm ci && cd docs && npm ci && cd ..
      build: npm run build:docs:preview
      output_dir: docs/public
