name: Primer Components Workflow
on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Publish to the npm registry
        uses: "primer/publish@c047b7c2646dd34b9f26a3e6a52c6393c07d7d52"
        with:
          args: "-- --unsafe-perm --allow-same-version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
