name: Primer Components
on: [push]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Publish to the npm registry
        uses: "primer/publish@dbf72c725e7eb6309aee73215e4fbcbe2b9c48f8"
        with:
          npm-args: "--unsafe-perm --allow-same-version"
          release-branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
