name: Canary Release
on:
  push:
    branches-ignore:
      - 'main'
      - 'next-major'
      - 'changeset-release/**'

jobs:
  release:
    concurrency: npm-canary
    uses: primer/.github/.github/workflows/release_canary.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
