name: Release

on:
  push:
    branches:
      - main
      - next-major

jobs:
  release-main:
    if: github.ref_name == 'main'
    steps:
      - id: get-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          client-id: ${{ vars.PRIMER_APP_CLIENT_ID_SHARED }}
          client-secret: ${{ secrets.PRIMER_APP_CLIENT_SECRET_SHARED }}
          installation-id: ${{ vars.PRIMER_APP_INSTALLATION_ID_SHARED }}
      - name: Main
        uses: primer/.github/.github/workflows/release.yml@main
        secrets:
          gh_token: ${{ steps.get-access-token.outputs.access-token }}
          npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}

  release-next-major:
    if: github.ref_name == 'next-major'
    steps:
      - id: get-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          client-id: ${{ vars.PRIMER_APP_CLIENT_ID_SHARED }}
          client-secret: ${{ secrets.PRIMER_APP_CLIENT_SECRET_SHARED }}
          installation-id: ${{ vars.PRIMER_APP_INSTALLATION_ID_SHARED }}
      - name: Next major
        uses: primer/.github/.github/workflows/release.yml@main
        with:
          title: Release tracking (next major)
        secrets:
          gh_token: ${{ steps.get-access-token.outputs.access-token }}
          npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
